spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

application:
  main-url: "https://api.nasa.gov/mars-photos/api/v1"
  rover: "curiosity"
  earth-date: "2020-6-3"
  camera: "FHAZ"
  api-key: "DEMO_KEY"