spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mars_photos?useSSL=false
    username: mars_photos
    password: user1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

application:
  main_url: "https://api.nasa.gov/mars-photos/api/v1"
  rover: "curiosity"
  earth_date: "2015-6-3"
  camera: "FHAZ"
  api_key: "DEMO_KEY"